import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../styles/globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import "@fortawesome/fontawesome-svg-core/styles";
import { config } from "@fortawesome/fontawesome-svg-core";
import {ToastContainer, Bounce} from "react-toastify"
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {Exo} from "next/font/google";
import Providers from "@/components/Providers/Providers";
import { verifyToken } from "@/features/auth/server/Token.action";
import { AuthState } from '../features/auth/store/auth.slice';
import { preloadedState } from '../store/store';
import { getLoggedUserCart } from "@/features/cart/server/cart.action";
import { CartState, setCartInfo } from "@/features/cart/store/Cart.slice";
import { getLoggedUserWishlist } from "@/features/wishlist/server/Wishlist.action";
import { setWishlistInfo, WishlistState } from "@/features/wishlist/store/Wishlist.slice";
const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400","500", "600", "700", "800", "900"],
});


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  let cartState:CartState = {
    cartId: null,
    numOfCartItems: 0,
    totalCartPrice: 0,
    products: [],
    error: null,
    isLoading: false
  }

  const authValues = await verifyToken()  //{isAuthenticated: true , userInfo}
  if(authValues.isAuthenticated){
    try {
      const cartResponse = await getLoggedUserCart()
      cartState ={
        cartId: cartResponse.cartId,
        numOfCartItems: cartResponse.numOfCartItems,
        totalCartPrice: cartResponse.data.totalCartPrice,
        products: cartResponse.data.products,
        error: null,
        isLoading: false
      }
    } catch (error) {
      
    }
  }

  let wishlistState:WishlistState = {
    count: 0,
    data: [],
    isLoading: false,
    error: null
  }

  if(authValues.isAuthenticated){
    try {
      const wishlistResponse = await getLoggedUserWishlist()
      // console.log(wishlistResponse);
      wishlistState = {
        count: wishlistResponse.count,
        data:wishlistResponse.data,
        error: null,
        isLoading: false
      }
      
    } catch (error) {
      
    }
  }

  return (
    <html lang="en">
      <body
        className={`${exo.className} font-medium`}
      >
        <Providers preloadedState={{auth:authValues, cart: cartState , wishlist: wishlistState  }} >
          <Navbar/>
        {children}
        <Footer/>
        <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        transition={Bounce}
        />
        </Providers>
      </body>
    </html>
  );
}
